### ISSUE TITLE
Remove need for process-dependency-links

### ISSUE THREAD

**Issue by muhrin** [muhrin/topika#1]
Currently topika depends on an unreleased (pre 1.0) commit of pika.  Unfortunately the older, released, versions don't expose enough functionality in their API for topika to work and the release `pika-dev` is too old.

We need to either:
* get an officially supported updated to `pika-dev`, or,
* release our own version on pypi

**Comment by PhilippRue** [comment]
comment, pika dependency in aiida-core should be updated accordingly if resolved

**Comment by muhrin** [comment]
@PhilippRue thanks for the reminder.  Yes, this has indeed been resolved thanks to @lukebakken releasing a dev version on pypi.  In this case AiiDA was not affected because it delegates to required version down to (I think), `kiwipy` which in turn is a dependency of `plumpy`.
